# Generated by Django 3.2.3 on 2021-05-25 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Message', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 25, 20, 28, 29, 790027))),
            ],
        ),
    ]
