# Generated by Django 3.2.3 on 2021-05-25 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 25, 21, 11, 43, 929952)),
        ),
        migrations.AlterField(
            model_name='message',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
