# Generated by Django 3.2.3 on 2021-05-25 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210525_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 25, 21, 12, 29, 424475)),
        ),
        migrations.AlterField(
            model_name='message',
            name='Message',
            field=models.TextField(max_length=500),
        ),
    ]
