# Generated by Django 3.2.3 on 2021-05-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_videoupload_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='Thumbnail',
            field=models.ImageField(upload_to='videos/Thumbnail'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='Video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
