# Generated by Django 3.2.3 on 2021-06-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_auto_20210618_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='videoID',
            field=models.IntegerField(null=True),
        ),
    ]
